<?php

use phpseclib3\Net\SFTP;

require_once(dirname(__FILE__) . '/../vendor/autoload.php');


$cms_user = getenv('MOVEIT_USERNAME');
$cms_pass = getenv('MOVEIT_PASSWORD');
$sftp = new SFTP('moveit.bcbsvt.com');
$sftp->setTimeout(300); // 5 minutes instead of default
$sftp->setKeepAlive(30); // Send keep-alive every 30 seconds
if (!$sftp->login($cms_user, $cms_pass)) {
    echo "login failed" . "\n";
    exit;
};

$path = '/Distribution/cms-reports/Prod/835';
$rawlist = $sftp->rawlist($path, true);
if (!empty($rawlist)) {
    foreach ($rawlist as $file) {
        if (!empty($file)) {
            if (!file_exists($file->filename)) {
                echo "a file's available: " . $file->filename . "\n";
                $dt_utc = new DateTimeImmutable(date('Y-m-d h:i:s a', $file->mtime));
                $date = $dt_utc->setTimezone(new DateTimeZone('America/New_York'));
                    echo "file: " . $file->filename . " created by 02 on " .
                $date->format('Y-m-d h:i:s a') . "\n";
            } else {
                echo "already grabbed " . $file->filename . " generated by 02 on " .
                    date('l jS \of F Y h:i:s A', $file->mtime) . "\n";
            }
        }
    }
} else {
    // there's a test directory
}

echo "end of list \n";
