<?php
use phpseclib3\Net\SFTP;

require_once(dirname(__FILE__) . '/../vendor/autoload.php');


$cms_user = getenv('MOVEIT_USERNAME');
$cms_pass = getenv('MOVEIT_PASSWORD');
$sftp = new SFTP('moveit.bcbsvt.com');
$sftp->setTimeout(300); // 5 minutes instead of default
$sftp->setKeepAlive(30); // Send keep-alive every 30 seconds
if (!$sftp->login($cms_user, $cms_pass)) {
    echo "login failed" . "\n";
    exit;
};

$path = '/Distribution/cms-reports/Prod/835';
//print_r($sftp->rawlist($path, true));

foreach(($sftp->rawlist($path, true)) as $file) {
    //var_dump($file);
    if (!file_exists($file->filename)) {
        echo "downloading " . $file->filename . "\n";
        $sftp->get($path . "/" . $file->filename, $file->filename);
    } else {
        echo "already grabbed " . $file->filename . " generated by 02 on " .
            date('l jS \of F Y h:i:s A',$file->mtime) . "\n";
    }
}