#!/bin/bash
#exec 2>> log1
#exec 1>> log1
#set -x

echo $(date)

cd vb

S20=charfile
S25=payfile
S30=parmndex
S35=claimfil
S40=patfile
S45=garfile
S50=insfile
S55=refphy
S60=procfile
S65=cmntfile
S70=authfile
S75=compfile
S80=mplrfile
S90=paycur
S95=addrfile
S100=rpgprocfile
S105=hospfile
S115=rpgactfile
S120=chchospfile
S125=hisfile
S130=batchfil
S140=kinfile
S200=../flat/flat_charfile
S250=../flat/flat_payfile
S300=../flat/flat_parmndex
S350=../flat/flat_claimfil
S400=../flat/flat_patfile
S450=../flat/flat_garfile
S500=../flat/flat_insfile
S550=../flat/flat_refphy
S600=../flat/flat_procfile
S650=../flat/flat_cmntfile
S700=../flat/flat_authfile
S750=../flat/flat_compfile
S800=../flat/flat_mplrfile
S900=../flat/flat_paycurx
S950=../flat/flat_addrfile
S1000=../flat/flat_rpgprocfile
S1050=../flat/flat_hospfile
S1150=../flat/flat_rpgactfile
S1200=../flat/flat_chchospfile
S1250=../flat/flat_hisfile
S1300=../flat/flat_batchfil
S1400=../flat/flat_kinfile
S1450=fileout


export S20 S25 S30 S35 S40 S45 S50 S55 S60 S65 S70
export S75 S80 S85 S90 S95 S100 S105 S115 S120 S125 S130 S135 S140
export S200 S250 S300 S350 S400 S450 S500 S550 S600 S650 S700
export S750 S800 S850 S900 S950 S1000 S1050 S1150 S1200 
export S1250 S1300 S1400 S1450

cobcrun ../so/cob000

unset S20 S25 S30 S35 S40 S45 S50 S55 S60 S65 S70
unset S75 S80 S85 S90 S95 S100 S105 S110 S115 S120 S125 S130
unset S200 S250 S300 S350 S400 S450 S500 S550 S600 S650 S700
unset S750 S800 S850 S900 S950 S1000 S1050 S1100 S1150 S1200 
unset S1250 S1300 S1400

echo $(date)

# emailauthssnfile

S135=emailauthssnfile
S1350=../flat/flat_emailauthssnfile
S1450=../log/errorfile
export S135 S1350 S1450
cobcrun ../so/email
unset S135 S1350 S1450

S30=charcur; S35=../flat/flat_charcur
export S30 S35
cobcrun ../so/cobr013
unset S30 S35

#exec 2> /dev/tty
#exec 1> /dev/tty

exit
