<?php
use phpseclib3\Net\SFTP;

require_once(dirname(__FILE__) . '/../vendor/autoload.php');

$ans = readline("era, enter 1, or 277, enter anything else, ? \n");
$cms_user = ($ans == 1) ? getenv('RRBERN_USERNAME') : getenv('RRB_USERNAME');
$cms_pass = getenv('RRB_PASSWORD');
$sftp = new SFTP('edi.palmetto.ahdsxhub.com', '22');
$sftp->login($cms_user, $cms_pass);

$path = '/inbox/EZComm/BC/1.0/Notify';

//print_r($sftp->rawlist($path, true));

foreach(($sftp->rawlist($path, true)) as $file) {
    //var_dump($file);
    if (!file_exists($file->filename)) {
        echo "downloading " . $file->filename . "\n";
        $sftp->get($path . "/" . $file->filename, $file->filename);
    } else {
        echo "already grabbed " . $file->filename . " generated by rrb on " .
            date('l jS \of F Y h:i:s A',$file->mtime) . "\n";
    }
}